jobs:
  - job: BuildDockerImage
    displayName: "Build Docker Image"
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: Docker@2
        displayName: "Build Docker Image"
        inputs:
          containerRegistry: ''          # blank here, push handles login
          repository: 'prmd77/temlate-image'
          command: 'build'
          Dockerfile: 'Dockerfile'    # Dockerfile path in repo
          tags: |
            latest
            $(Build.BuildId)